### ISSUE TITLE
NZBtoMedia problem when updating to V24 on Synology/Docker

### ISSUE THREAD

**Issue by ronrosenfeld** [nzbgetcom/nzbget#296]
### Is there already an issue for this request?

- [X] I have checked older issues, open and closed

### Describe your issue

I recently upgraded nzbGet from v21 to v24. Unfortunately, nzbToMedia now seems to be failing. Not sure why. 
Worked fine with v21.
System: Docker on Synology. running SickChill and nzbGet packages

After updating I noted that the option to run extension scripts was deselected for my `tv` category, but I reselected it. 
When running the post-process routine, I see this in the log:

```
Mon Jun 10 18:13:46 2024	1718057626	INFO	Executing post-process-script nzbToMedia for The.Acolyte.S01E01.1080p.DSNP.WEB-DL.DDP5.1.H.264-KWK
Mon Jun 10 18:13:46 2024	1718057626	INFO	nzbToMedia: Traceback (most recent call last):
Mon Jun 10 18:13:46 2024	1718057626	INFO	nzbToMedia:   File "/downloads/scripts/nzbToMedia.old/nzbToMedia.py", line 520, in <module>
Mon Jun 10 18:13:46 2024	1718057626	INFO	nzbToMedia:     import core
Mon Jun 10 18:13:46 2024	1718057626	INFO	nzbToMedia:   File "/downloads/scripts/nzbToMedia.old/core/__init__.py", line 33, in <module>
Mon Jun 10 18:13:46 2024	1718057626	INFO	nzbToMedia:     from six.moves import reload_module
Mon Jun 10 18:13:46 2024	1718057626	INFO	nzbToMedia: ModuleNotFoundError: No module named 'six.moves'
Mon Jun 10 18:13:46 2024	1718057626	ERROR	Post-process-script nzbToMedia for xxxxxxx.S01E01.1080p.DSNP.WEB-DL.DDP5.1.H.264-KWK failed (terminated with unknown status)
```
Any suggestions appreciated. 

By the way, on a different machine running Windows, I was able to update to V24 and, after dealing with the missing Script designation for the `tv` category, it seems to be working fine.

**Comment by luckedea** [comment]
@ronrosenfeld Can you please tell more about your setup?
Which version of extension, What version of python in the docker, you installed/upgraded how exactly? Is this linuxserver or our nzbgetcom container?

**Comment by luckedea** [comment]
@ronrosenfeld 

It's not clear what version of nzbtomedia you have. Can you please share? It doesn't look like an old version of 
https://github.com/clinton-hall/nzbToMedia - however extension itself should be working fine - I suggest you try the later version please?

I can also suggest NotifySickChill which is supported by us through Extension Manager.

**Comment by ronrosenfeld** [comment]
@luckedea  I updated to the "nightly" branch of nzbToMedia.
Still getting errors, but they are different:

```
Tue Jun 11 10:46:49 2024	1718117209	INFO	Post-processing again xxxxxxxxxx.2024.06.10.1080p.WEB.H264-JEBAITED
Tue Jun 11 10:46:49 2024	1718117209	INFO	xxxxxxxxxx.2024.06.10.1080p.WEB.H264-JEBAITED returned from history back to download queue
Tue Jun 11 10:46:49 2024	1718117209	INFO	Queueing xxxxxxxxxx.2024.06.10.1080p.WEB.H264-JEBAITED for post-processing
Tue Jun 11 10:46:50 2024	1718117210	INFO	Cleaning up xxxxxxxxxx.2024.06.10.1080p.WEB.H264-JEBAITED
Tue Jun 11 10:46:50 2024	1718117210	INFO	Nothing to cleanup for xxxxxxxxxx.2024.06.10.1080p.WEB.H264-JEBAITED
Tue Jun 11 10:46:50 2024	1718117210	INFO	Executing post-process-script nzbToMedia for xxxxxxxxxx.2024.06.10.1080p.WEB.H264-JEBAITED
Tue Jun 11 10:46:51 2024	1718117211	INFO	nzbToMedia: Changing to directory: /downloads/scripts/nzbToMedia.old
Tue Jun 11 10:46:51 2024	1718117211	INFO	nzbToMedia: -- Cleaning bytecode --
Tue Jun 11 10:46:51 2024	1718117211	INFO	nzbToMedia: WARNING: Automatic cleanup could not be executed.
Tue Jun 11 10:46:51 2024	1718117211	INFO	nzbToMedia:          If errors occur, manual cleanup may be required.
Tue Jun 11 10:46:51 2024	1718117211	INFO	nzbToMedia: REASON : Error: [Errno 2] No such file or directory: 'git'
Tue Jun 11 10:46:51 2024	1718117211	INFO	nzbToMedia: -- Cleaning folders: ['libs', 'core'] --
Tue Jun 11 10:46:51 2024	1718117211	INFO	nzbToMedia: WARNING: Automatic cleanup could not be executed.
Tue Jun 11 10:46:51 2024	1718117211	INFO	nzbToMedia:          If errors occur, manual cleanup may be required.
Tue Jun 11 10:46:51 2024	1718117211	INFO	nzbToMedia: REASON : Error: [Errno 2] No such file or directory: 'git'
Tue Jun 11 10:46:51 2024	1718117211	INFO	nzbToMedia: Returning to directory:  /run/s6-rc:s6-rc-init:dfLjOo/servicedirs/svc-nzbget
Tue Jun 11 10:46:51 2024	1718117211	INFO	nzbToMedia: -- Cleanup finished --
Tue Jun 11 10:46:51 2024	1718117211	INFO	nzbToMedia: Traceback (most recent call last):
Tue Jun 11 10:46:51 2024	1718117211	INFO	nzbToMedia:   File "/downloads/scripts/nzbToMedia.old/nzbToMedia.py", line 734, in <module>
Tue Jun 11 10:46:51 2024	1718117211	INFO	nzbToMedia:     import core
Tue Jun 11 10:46:51 2024	1718117211	INFO	nzbToMedia:   File "/downloads/scripts/nzbToMedia.old/core/__init__.py", line 52, in <module>
Tue Jun 11 10:46:51 2024	1718117211	INFO	nzbToMedia:     from core import logger, main_db, version_check, databases, transcoder
Tue Jun 11 10:46:51 2024	1718117211	INFO	nzbToMedia: ImportError: bad magic number in 'core.databases': b'\x03\xf3\r\n'
Tue Jun 11 10:46:51 2024	1718117211	ERROR	Post-process-script nzbToMedia for xxxxxxxxxx.2024.06.10.1080p.WEB.H264-JEBAITED failed (terminated with unknown status)
Tue Jun 11 10:46:51 2024	1718117211	INFO	Collection xxxxxxxxxx.2024.06.10.1080p.WEB.H264-JEBAITED added to history
```

**Comment by phnzb** [comment]
@ronrosenfeld
Can you try using nzbToSickBeard plugin instead of the one you are using? I have tested:
nzbget v24.1 (docker)
nzbToMedia v12.1.13 (latest release)
SickChill 2024.3.1 (docker)

used nzbToSickBeard settings:
sbhost: my_sick_chill_ip
sbapikey: my_api_key
sbfork: auto
sbprocess_method: move

Reference manual to setup nzbToMedia:

https://github.com/SickChill/SickChill/wiki/NZBtoMedia#how-to-setup-nzbtomedia-with-nzbget

**Comment by ronrosenfeld** [comment]
I will give it a try. But I am out of town for a few weeks so will try that when I get back.

Thanks.

Ron
________________________________

**Comment by ronrosenfeld** [comment]
OK, I gave it a try.
Same versions and set-up as you show, except I do not know how to determine the nzbToMedia version. But it should be the latest as I just did a `git checkout nightly` and `git pull` and received message that it was up to date.

Still not working Returning `PP-FAILURE`

```
Mon Jun 17 15:19:02 2024	1718651942	INFO	Post-processing again xxxx.xxxx.xxxx.xxxx.xxxxx.S22E19.1080p.HEVC.x265-MeGusta
Mon Jun 17 15:19:02 2024	1718651942	INFO	xxxx.xxxx.xxxx.xxxx.xxxxx.S22E19.1080p.HEVC.x265-MeGusta returned from history back to download queue
Mon Jun 17 15:19:02 2024	1718651942	INFO	Queueing xxxx.xxxx.xxxx.xxxx.xxxxx.S22E19.1080p.HEVC.x265-MeGusta for post-processing
Mon Jun 17 15:19:03 2024	1718651943	INFO	Cleaning up xxxx.xxxx.xxxx.xxxx.xxxxx.S22E19.1080p.HEVC.x265-MeGusta
Mon Jun 17 15:19:03 2024	1718651943	INFO	Nothing to cleanup for xxxx.xxxx.xxxx.xxxx.xxxxx.S22E19.1080p.HEVC.x265-MeGusta
Mon Jun 17 15:19:03 2024	1718651943	INFO	Executing post-process-script nzbToSickBeard for xxxx.xxxx.xxxx.xxxx.xxxxx.S22E19.1080p.HEVC.x265-MeGusta
Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard: Changing to directory: /downloads/scripts/nzbToMedia
Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard: -- Cleaning bytecode --
Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard: WARNING: Automatic cleanup could not be executed.
Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard:          If errors occur, manual cleanup may be required.
Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard: REASON : Error: [Errno 2] No such file or directory: 'git'
Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard: -- Cleaning folders: ['libs', 'core'] --
Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard: WARNING: Automatic cleanup could not be executed.
Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard:          If errors occur, manual cleanup may be required.
Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard: REASON : Error: [Errno 2] No such file or directory: 'git'
Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard: Returning to directory:  /run/s6-rc:s6-rc-init:ohpMfM/servicedirs/svc-nzbget
Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard: -- Cleanup finished --
Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard: Traceback (most recent call last):
Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard:   File "/downloads/scripts/nzbToMedia/nzbToSickBeard.py", line 275, in <module>
Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard:     import nzbToMedia
Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard:   File "/downloads/scripts/nzbToMedia/nzbToMedia.py", line 734, in <module>
Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard:     import core
Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard:   File "/downloads/scripts/nzbToMedia/core/__init__.py", line 52, in <module>
Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard:     from core import logger, main_db, version_check, databases, transcoder
Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard: ImportError: bad magic number in 'core.databases': b'\x03\xf3\r\n'
Mon Jun 17 15:19:04 2024	1718651944	ERROR	Post-process-script nzbToSickBeard for xxxx.xxxx.xxxx.xxxx.xxxxx.S22E19.1080p.HEVC.x265-MeGusta failed (terminated with unknown status)
Mon Jun 17 15:19:04 2024	1718651944	INFO	Collection xxxx.xxxx.xxxx.xxxx.xxxxx.S22E19.1080p.HEVC.x265-MeGusta added to history
```
I'd hate to reinstall everything and then have it still not work <sigh>. Any other thoughts?
Thanks.
   Ron

**Comment by luckedea** [comment]
@ronrosenfeld While we are looking into it, did you consider NotifySickChill extension? Or you specifically need nzbtomedia?
NotifySickChill is an extension we support and installation is easy using Extension Manager.

**Comment by ronrosenfeld** [comment]
No, I haven't tried it. I need find the extension manager and figure out how to add it in.

I am surprised that the similar process of updating from version 21 on Windows worked with minimal difficulty and I'm having so much trouble with the update in docker.

And no, I just need a mechanism to notify sickchill to do the post-processing and also take care of the failed downloads issue.

Does your extension do both?

Ron








________________________________

**Comment by ronrosenfeld** [comment]
@luckedea 
OK, I enabled `NotifySickchill` and it does seem to work to trigger post-processing. And it seems that it also handles failed downloads. Looking at the other available extensions, is it worthwhile to enable `FakeDetector`. Any others I should consider? Thanks.
Ron

**Comment by luckedea** [comment]
> @luckedea OK, I gave it a try. Same versions and set-up as you show, except I do not know how to determine the nzbToMedia version. But it should be the latest as I just did a `git checkout nightly` and `git pull` and received message that it was up to date.
> 
> Still not working Returning `PP-FAILURE`
> 
> ```
> Mon Jun 17 15:19:02 2024	1718651942	INFO	Post-processing again xxxx.xxxx.xxxx.xxxx.xxxxx.S22E19.1080p.HEVC.x265-MeGusta
> Mon Jun 17 15:19:02 2024	1718651942	INFO	xxxx.xxxx.xxxx.xxxx.xxxxx.S22E19.1080p.HEVC.x265-MeGusta returned from history back to download queue
> Mon Jun 17 15:19:02 2024	1718651942	INFO	Queueing xxxx.xxxx.xxxx.xxxx.xxxxx.S22E19.1080p.HEVC.x265-MeGusta for post-processing
> Mon Jun 17 15:19:03 2024	1718651943	INFO	Cleaning up xxxx.xxxx.xxxx.xxxx.xxxxx.S22E19.1080p.HEVC.x265-MeGusta
> Mon Jun 17 15:19:03 2024	1718651943	INFO	Nothing to cleanup for xxxx.xxxx.xxxx.xxxx.xxxxx.S22E19.1080p.HEVC.x265-MeGusta
> Mon Jun 17 15:19:03 2024	1718651943	INFO	Executing post-process-script nzbToSickBeard for xxxx.xxxx.xxxx.xxxx.xxxxx.S22E19.1080p.HEVC.x265-MeGusta
> Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard: Changing to directory: /downloads/scripts/nzbToMedia
> Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard: -- Cleaning bytecode --
> Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard: WARNING: Automatic cleanup could not be executed.
> Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard:          If errors occur, manual cleanup may be required.
> Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard: REASON : Error: [Errno 2] No such file or directory: 'git'
> Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard: -- Cleaning folders: ['libs', 'core'] --
> Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard: WARNING: Automatic cleanup could not be executed.
> Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard:          If errors occur, manual cleanup may be required.
> Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard: REASON : Error: [Errno 2] No such file or directory: 'git'
> Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard: Returning to directory:  /run/s6-rc:s6-rc-init:ohpMfM/servicedirs/svc-nzbget
> Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard: -- Cleanup finished --
> Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard: Traceback (most recent call last):
> Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard:   File "/downloads/scripts/nzbToMedia/nzbToSickBeard.py", line 275, in <module>
> Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard:     import nzbToMedia
> Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard:   File "/downloads/scripts/nzbToMedia/nzbToMedia.py", line 734, in <module>
> Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard:     import core
> Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard:   File "/downloads/scripts/nzbToMedia/core/__init__.py", line 52, in <module>
> Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard:     from core import logger, main_db, version_check, databases, transcoder
> Mon Jun 17 15:19:04 2024	1718651944	INFO	nzbToSickBeard: ImportError: bad magic number in 'core.databases': b'\x03\xf3\r\n'
> Mon Jun 17 15:19:04 2024	1718651944	ERROR	Post-process-script nzbToSickBeard for xxxx.xxxx.xxxx.xxxx.xxxxx.S22E19.1080p.HEVC.x265-MeGusta failed (terminated with unknown status)
> Mon Jun 17 15:19:04 2024	1718651944	INFO	Collection xxxx.xxxx.xxxx.xxxx.xxxxx.S22E19.1080p.HEVC.x265-MeGusta added to history
> ```
> 
> I'd hate to reinstall everything and then have it still not work . Any other thoughts? Thanks. Ron

Sorry for the troubles, it's all py2=>py3 migration.
For nzbtomedia you can try deleting *.pyc files. But ideally perform a clean install of nzbtomedia.

Happy that NotifySickChill worked out for you.

**Comment by ronrosenfeld** [comment]
@luckedea 

I suspected it might have something to do with Python versions, but your nzbToSickBeard plugin seems to work OK, so I'll probably just stick with that, at least on the Docker/Synology set up.

Thank you for your patience with me.

Ron
